name: CI/CD

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PASS}}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.0
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            machadoluiz/kube-news:latest
            machadoluiz/kube-news:${{github.run_number}}
            
  CD:
    runs-on: ubuntu-latest
    needs: [CI]

    steps:
      - uses: actions/checkout@v3
      
      - name: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{secrets.GCP_ACCOUNT}}

      - name: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v0'
        with:
          cluster_name: 'cluster-3'
          location: us-east1

      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v4.3
        with:
          images: machadoluiz/kube-news:${{github.run_number}}
          manifests: k8s/deployment.yaml
