name: CI/CD

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PASS}}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.0
        with:
          context: .src/
          file: ./Dockerfile
          push: true
          tags: |
            machadoluiz/kube-news:latest
            machadoluiz/kube-news:${{github.run_number}}
            
